server:
  port: 8081
  
spring:
  application:
    name: taotao-web
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
    type: 
  jpa:
    database: mysql
    database-platform: 
    hibernate:
      ddl-auto: none
    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
  reasonable: true
  params: count=countSql